// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/CalcProto.proto

#include "test/CalcProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace test {
class CalcCommandProtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CalcCommandProto>
      _instance;
} _CalcCommandProto_default_instance_;
class CalcResultProtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CalcResultProto>
      _instance;
} _CalcResultProto_default_instance_;
}  // namespace test
namespace protobuf_test_2fCalcProto_2eproto {
static void InitDefaultsCalcCommandProto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::test::_CalcCommandProto_default_instance_;
    new (ptr) ::test::CalcCommandProto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::test::CalcCommandProto::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CalcCommandProto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCalcCommandProto}, {}};

static void InitDefaultsCalcResultProto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::test::_CalcResultProto_default_instance_;
    new (ptr) ::test::CalcResultProto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::test::CalcResultProto::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CalcResultProto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCalcResultProto}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CalcCommandProto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CalcResultProto.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::CalcCommandProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::CalcCommandProto, command_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::CalcCommandProto, op_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::CalcCommandProto, var1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::CalcCommandProto, var2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::CalcCommandProto, var_more_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::CalcResultProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::CalcResultProto, result_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::test::CalcCommandProto)},
  { 10, -1, sizeof(::test::CalcResultProto)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::test::_CalcCommandProto_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::test::_CalcResultProto_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "test/CalcProto.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024test/CalcProto.proto\022\004test\"\247\001\n\020CalcCom"
      "mandProto\022\024\n\014command_name\030\001 \001(\t\022,\n\007op_ty"
      "pe\030\002 \001(\0162\033.test.CalcCommandProto.Type\022\014\n"
      "\004var1\030\003 \001(\005\022\014\n\004var2\030\004 \001(\005\022\020\n\010var_more\030\005 "
      "\003(\005\"!\n\004Type\022\007\n\003ADD\020\000\022\007\n\003SUB\020\001\022\007\n\003MUL\020\002\"!"
      "\n\017CalcResultProto\022\016\n\006result\030\001 \001(\005b\006proto"
      "3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 241);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "test/CalcProto.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_test_2fCalcProto_2eproto
namespace test {
const ::google::protobuf::EnumDescriptor* CalcCommandProto_Type_descriptor() {
  protobuf_test_2fCalcProto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_test_2fCalcProto_2eproto::file_level_enum_descriptors[0];
}
bool CalcCommandProto_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const CalcCommandProto_Type CalcCommandProto::ADD;
const CalcCommandProto_Type CalcCommandProto::SUB;
const CalcCommandProto_Type CalcCommandProto::MUL;
const CalcCommandProto_Type CalcCommandProto::Type_MIN;
const CalcCommandProto_Type CalcCommandProto::Type_MAX;
const int CalcCommandProto::Type_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void CalcCommandProto::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CalcCommandProto::kCommandNameFieldNumber;
const int CalcCommandProto::kOpTypeFieldNumber;
const int CalcCommandProto::kVar1FieldNumber;
const int CalcCommandProto::kVar2FieldNumber;
const int CalcCommandProto::kVarMoreFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CalcCommandProto::CalcCommandProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_test_2fCalcProto_2eproto::scc_info_CalcCommandProto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:test.CalcCommandProto)
}
CalcCommandProto::CalcCommandProto(const CalcCommandProto& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      var_more_(from.var_more_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  command_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.command_name().size() > 0) {
    command_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.command_name_);
  }
  ::memcpy(&op_type_, &from.op_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&var2_) -
    reinterpret_cast<char*>(&op_type_)) + sizeof(var2_));
  // @@protoc_insertion_point(copy_constructor:test.CalcCommandProto)
}

void CalcCommandProto::SharedCtor() {
  command_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&op_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&var2_) -
      reinterpret_cast<char*>(&op_type_)) + sizeof(var2_));
}

CalcCommandProto::~CalcCommandProto() {
  // @@protoc_insertion_point(destructor:test.CalcCommandProto)
  SharedDtor();
}

void CalcCommandProto::SharedDtor() {
  command_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CalcCommandProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CalcCommandProto::descriptor() {
  ::protobuf_test_2fCalcProto_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test_2fCalcProto_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CalcCommandProto& CalcCommandProto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_test_2fCalcProto_2eproto::scc_info_CalcCommandProto.base);
  return *internal_default_instance();
}


void CalcCommandProto::Clear() {
// @@protoc_insertion_point(message_clear_start:test.CalcCommandProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  var_more_.Clear();
  command_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&op_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&var2_) -
      reinterpret_cast<char*>(&op_type_)) + sizeof(var2_));
  _internal_metadata_.Clear();
}

bool CalcCommandProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:test.CalcCommandProto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string command_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_command_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->command_name().data(), static_cast<int>(this->command_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "test.CalcCommandProto.command_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .test.CalcCommandProto.Type op_type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_op_type(static_cast< ::test::CalcCommandProto_Type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 var1 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &var1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 var2 = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &var2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 var_more = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_var_more())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 42u, input, this->mutable_var_more())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:test.CalcCommandProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:test.CalcCommandProto)
  return false;
#undef DO_
}

void CalcCommandProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:test.CalcCommandProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string command_name = 1;
  if (this->command_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->command_name().data(), static_cast<int>(this->command_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "test.CalcCommandProto.command_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->command_name(), output);
  }

  // .test.CalcCommandProto.Type op_type = 2;
  if (this->op_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->op_type(), output);
  }

  // int32 var1 = 3;
  if (this->var1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->var1(), output);
  }

  // int32 var2 = 4;
  if (this->var2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->var2(), output);
  }

  // repeated int32 var_more = 5;
  if (this->var_more_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(5, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _var_more_cached_byte_size_));
  }
  for (int i = 0, n = this->var_more_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->var_more(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:test.CalcCommandProto)
}

::google::protobuf::uint8* CalcCommandProto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:test.CalcCommandProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string command_name = 1;
  if (this->command_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->command_name().data(), static_cast<int>(this->command_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "test.CalcCommandProto.command_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->command_name(), target);
  }

  // .test.CalcCommandProto.Type op_type = 2;
  if (this->op_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->op_type(), target);
  }

  // int32 var1 = 3;
  if (this->var1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->var1(), target);
  }

  // int32 var2 = 4;
  if (this->var2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->var2(), target);
  }

  // repeated int32 var_more = 5;
  if (this->var_more_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      5,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _var_more_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->var_more_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:test.CalcCommandProto)
  return target;
}

size_t CalcCommandProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:test.CalcCommandProto)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated int32 var_more = 5;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->var_more_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _var_more_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string command_name = 1;
  if (this->command_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->command_name());
  }

  // .test.CalcCommandProto.Type op_type = 2;
  if (this->op_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->op_type());
  }

  // int32 var1 = 3;
  if (this->var1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->var1());
  }

  // int32 var2 = 4;
  if (this->var2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->var2());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CalcCommandProto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:test.CalcCommandProto)
  GOOGLE_DCHECK_NE(&from, this);
  const CalcCommandProto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CalcCommandProto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:test.CalcCommandProto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:test.CalcCommandProto)
    MergeFrom(*source);
  }
}

void CalcCommandProto::MergeFrom(const CalcCommandProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:test.CalcCommandProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  var_more_.MergeFrom(from.var_more_);
  if (from.command_name().size() > 0) {

    command_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.command_name_);
  }
  if (from.op_type() != 0) {
    set_op_type(from.op_type());
  }
  if (from.var1() != 0) {
    set_var1(from.var1());
  }
  if (from.var2() != 0) {
    set_var2(from.var2());
  }
}

void CalcCommandProto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:test.CalcCommandProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CalcCommandProto::CopyFrom(const CalcCommandProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:test.CalcCommandProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CalcCommandProto::IsInitialized() const {
  return true;
}

void CalcCommandProto::Swap(CalcCommandProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CalcCommandProto::InternalSwap(CalcCommandProto* other) {
  using std::swap;
  var_more_.InternalSwap(&other->var_more_);
  command_name_.Swap(&other->command_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(op_type_, other->op_type_);
  swap(var1_, other->var1_);
  swap(var2_, other->var2_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CalcCommandProto::GetMetadata() const {
  protobuf_test_2fCalcProto_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test_2fCalcProto_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CalcResultProto::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CalcResultProto::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CalcResultProto::CalcResultProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_test_2fCalcProto_2eproto::scc_info_CalcResultProto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:test.CalcResultProto)
}
CalcResultProto::CalcResultProto(const CalcResultProto& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  result_ = from.result_;
  // @@protoc_insertion_point(copy_constructor:test.CalcResultProto)
}

void CalcResultProto::SharedCtor() {
  result_ = 0;
}

CalcResultProto::~CalcResultProto() {
  // @@protoc_insertion_point(destructor:test.CalcResultProto)
  SharedDtor();
}

void CalcResultProto::SharedDtor() {
}

void CalcResultProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CalcResultProto::descriptor() {
  ::protobuf_test_2fCalcProto_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test_2fCalcProto_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CalcResultProto& CalcResultProto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_test_2fCalcProto_2eproto::scc_info_CalcResultProto.base);
  return *internal_default_instance();
}


void CalcResultProto::Clear() {
// @@protoc_insertion_point(message_clear_start:test.CalcResultProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  result_ = 0;
  _internal_metadata_.Clear();
}

bool CalcResultProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:test.CalcResultProto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 result = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:test.CalcResultProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:test.CalcResultProto)
  return false;
#undef DO_
}

void CalcResultProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:test.CalcResultProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:test.CalcResultProto)
}

::google::protobuf::uint8* CalcResultProto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:test.CalcResultProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:test.CalcResultProto)
  return target;
}

size_t CalcResultProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:test.CalcResultProto)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 result = 1;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->result());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CalcResultProto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:test.CalcResultProto)
  GOOGLE_DCHECK_NE(&from, this);
  const CalcResultProto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CalcResultProto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:test.CalcResultProto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:test.CalcResultProto)
    MergeFrom(*source);
  }
}

void CalcResultProto::MergeFrom(const CalcResultProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:test.CalcResultProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.result() != 0) {
    set_result(from.result());
  }
}

void CalcResultProto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:test.CalcResultProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CalcResultProto::CopyFrom(const CalcResultProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:test.CalcResultProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CalcResultProto::IsInitialized() const {
  return true;
}

void CalcResultProto::Swap(CalcResultProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CalcResultProto::InternalSwap(CalcResultProto* other) {
  using std::swap;
  swap(result_, other->result_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CalcResultProto::GetMetadata() const {
  protobuf_test_2fCalcProto_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test_2fCalcProto_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace test
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::test::CalcCommandProto* Arena::CreateMaybeMessage< ::test::CalcCommandProto >(Arena* arena) {
  return Arena::CreateInternal< ::test::CalcCommandProto >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::test::CalcResultProto* Arena::CreateMaybeMessage< ::test::CalcResultProto >(Arena* arena) {
  return Arena::CreateInternal< ::test::CalcResultProto >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
