/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cch_HelloApp_MainActivity */

#ifndef _Included_com_cch_HelloApp_MainActivity
#define _Included_com_cch_HelloApp_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cch_HelloApp_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cch_HelloApp_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
