/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: person.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "person.pb-c.h"
void   company__init
                     (Company         *message)
{
  static const Company init_value = COMPANY__INIT;
  *message = init_value;
}
size_t company__get_packed_size
                     (const Company *message)
{
  assert(message->base.descriptor == &company__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t company__pack
                     (const Company *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &company__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t company__pack_to_buffer
                     (const Company *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &company__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Company *
       company__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Company *)
     protobuf_c_message_unpack (&company__descriptor,
                                allocator, len, data);
}
void   company__free_unpacked
                     (Company *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &company__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   person__init
                     (Person         *message)
{
  static const Person init_value = PERSON__INIT;
  *message = init_value;
}
size_t person__get_packed_size
                     (const Person *message)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t person__pack
                     (const Person *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t person__pack_to_buffer
                     (const Person *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Person *
       person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Person *)
     protobuf_c_message_unpack (&person__descriptor,
                                allocator, len, data);
}
void   person__free_unpacked
                     (Person *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &person__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor company__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Company, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Company, address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "salary",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Company, salary),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned company__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = name */
  2,   /* field[2] = salary */
};
static const ProtobufCIntRange company__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor company__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Company",
  "Company",
  "Company",
  "",
  sizeof(Company),
  3,
  company__field_descriptors,
  company__field_indices_by_name,
  1,  company__number_ranges,
  (ProtobufCMessageInit) company__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor person__field_descriptors[8] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Person, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Person, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "email",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Person, email),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scores",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Person, n_scores),
    offsetof(Person, scores),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gender",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Person, gender),
    &gender__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Person, contact_case),
    offsetof(Person, address),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Person, contact_case),
    offsetof(Person, phone),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "companys",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Person, n_companys),
    offsetof(Person, companys),
    &company__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned person__field_indices_by_name[] = {
  5,   /* field[5] = address */
  7,   /* field[7] = companys */
  2,   /* field[2] = email */
  4,   /* field[4] = gender */
  1,   /* field[1] = id */
  0,   /* field[0] = name */
  6,   /* field[6] = phone */
  3,   /* field[3] = scores */
};
static const ProtobufCIntRange person__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor person__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Person",
  "Person",
  "Person",
  "",
  sizeof(Person),
  8,
  person__field_descriptors,
  person__field_indices_by_name,
  1,  person__number_ranges,
  (ProtobufCMessageInit) person__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue gender__enum_values_by_number[2] =
{
  { "MALE", "GENDER__MALE", 0 },
  { "FAMALE", "GENDER__FAMALE", 1 },
};
static const ProtobufCIntRange gender__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex gender__enum_values_by_name[2] =
{
  { "FAMALE", 1 },
  { "MALE", 0 },
};
const ProtobufCEnumDescriptor gender__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Gender",
  "Gender",
  "Gender",
  "",
  2,
  gender__enum_values_by_number,
  2,
  gender__enum_values_by_name,
  1,
  gender__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
